language: java
branches:
  only:
  - master
script: mvn clean package
deploy:
  provider: bintray
  file: .bintray.json
  user: jpenninkhof
  key:
    secure: A0QtfNs0sJOJFAhiw+qsPQL063HOstW3DCMr0Y3fY2dJmVa1jlIdQ741dJbdLN/6BT40BsnJ4TU/3yk/YGzDfNk00kdPgP+xCFNUvJ/X16KtHwfb+xMeCOY0rimShrU5YFb2amO9KI5fvw89VLCep0OI81lmCy3PW4nvuSzIoME+kwvg7bP01kuBtnzkU0FlOMToiFN5A0EJwQ9LyhFJbh093i348sG8zUzFl2OT4199ZqJKQlFjhDsgK2f7Ax52pSZXiExeTxA68owO0Ta5QzB1hID72ZxxwzuBoAszdsciRMyFEWO6ItYN2Qqt+fX1TzXWGnvdwjKYutcCHfDVeiJoqNP+JcNCDeIE9i/HTLv8/9P+Re2tInmvMxPVpZmWOW+XWt1oAujJPO61MQZEgdTiwqKT5JxCQrOE8tsB9hkVNxVFCrEQcQHDux2feO2VPCF0c25b0FfoRpJ3t+5kuwIT+uFTVbCDJQY5qMezlzrtsuUePlbjBwsyM5TVL86oouuXc9Yrq4awmiMpsMN5UcUpm1mMR0EZbx5x2gQQPzSfBsvk92Bx1Xwf7IXylflVcsImv2UbWGBnn/HcVy4PLWPFv616gd7fqVUlkCoHYMEUcGhTLwuf6MNl4sJALjAPeh8l1hO4pIyY6AkEh3IS+P6ZSvlBPCNzSZCe6pQ0+IY=
